class DropDownMenuConstant {


  static List<String> stateItems = [
    'KPK',
    'PUNJAB',
    'BALOCHISTAN',
    'SINDH',
    'GILGIT' 'BALTISTAN',
    'KASHMIR'
  ];

  static List<String> districtItems = [
    ' Abbottabad',
    ' Astore',
    ' Attock',
    ' Awaran',
    ' Badin',
    ' Bagh',
    ' Bahawalnagar',
    ' Bahawalpur',
    ' Bajaur',
    ' Bannu',
    ' Barkhan',
    ' Batagram',
    ' Bhakkar',
    ' Bhimber',
    ' Buner',
    ' Chagai',
    ' Chakwal',
    ' Charsadda',
    ' Chiniot',
    ' Dadu',
    ' Darel',
    ' Dera Bugti',
    'Dera Ghazi Khan',
    'Dera Ismail Khan',
    'Diamer',
    'Duki',
    'Faisalabad',
    'Ghanche',
    'Ghizer',
    'Ghotki',
    'Gilgit',
    'Gujranwala',
    'Gujrat',
    'Gupis Yasin',
    'Gwadar',
    'Hafizabad',
    'Hangu',
    'Haripur',
    'Harnai',
    'Hattian',
    'Haveli',
    'Hunza',
    'Hyderabad',
    'Islamabad',
    'Jacobabad',
    'Jafarabad',
    'Jamshoro',
    'Jhal Magsi',
    'Jhang',
    'Jhelum',
    'Kachhi',
    'Kalat',
    'Karachi Central',
    'Karachi East',
    'Karachi South',
    'Karachi West',
    'Karak',
    'Kashmore',
    'Kasur',
    'Kech',
    'Khairpur',
    'Khanewal',
    'Kharan',
    'Kharmang',
    'Khushab',
    'Khuzdar',
    'Khyber',
    'Killa Abdullah',
    'Kohat',
    'Kohlu',
    'Kolai Pallas',
    'Korangi',
    'Kotli',
    'Kurram',
    'Lahore',
    'Lakki Marwat',
    'Larkana',
    'Lasbela',
    'Layyah',
    'Lodhran',
    'Loralai',
    'Lower Chitral',
    'Lower Dir',
    'Lower Kohistan',
    'Malakand',
    'Malir',
    'Mandi Bahauddin',
    'Mansehra',
    'Mardan',
    'Mastung',
    'Matiari',
    'Mianwali',
    'Mirpur Khas',
    'Mirpur',
    'Mohmand',
    'Multan',
    'Musakhel',
    'Muzaffarabad',
    'Muzaffargarh',
    'Nagar',
    'Nankana Sahib',
    'Narowal',
    'Naseerabad',
    'Naushahro Firoze',
    'Neelum',
    'North Waziristan',
    'Nowshera',
    'Nushki',
    'Okara',
    'Orakzai',
    'Pakpattan',
    'Panjgur',
    'Peshawar',
    'Pishin',
    'Poonch',
    'Qambar Shahdadkot',
    'Qilla Saifullah',
    'Quetta',
    'Rahim Yar Khan',
    'Rajanpur',
    'Rawalpindi',
    'Roundu',
    'Sahiwal',
    'Sanghar',
    'Sargodha',
    'Shaheed Benazirabad',
    'Shaheed Sikandarabad',
    'Shangla',
    'Sheikhupura',
    'Sherani',
    'Shigar',
    'Shikarpur',
    'Sialkot',
    'Sibi',
    'Skardu',
    'Sohbatpur',
    'South Waziristan',
    'Sudhnutti',
    'Sujawal',
    'Sukkur',
    'Swabi',
    'Swat',
    'Tando Allahyar',
    'Tando Muhammad Khan',
    'Tangir',
    'Tank',
    'Tharparkar',
    'Thatta',
    'Toba Tek Singh',
    'Tor Ghar',
    'Umerkot',
    'Upper Chitral',
    'Upper Dir',
    'Upper Kohistan',
    'Vehari',
    'Washuk',
    'Zhob',
    'Ziarat',
  ];

  static List<String> countriesItems = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo, Democratic Republic of the",
    "Congo, Republic of the",
    "Costa Rica",
    "Cote d'Ivoire",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar (Burma)",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Korea",
    "North Macedonia (formerly Macedonia)",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine",
    "Panama",
    "Papua New",
  ];


  static List<String> bloodGroups = [
    "A+",
    "A-",
    "B+",
    "B-",
    "AB+",
    "AB-",
    "O+",
    "O-"
  ];


  static List<String> genderItems = [
   "Male","Female","Other"
  ];



}